#!/usr/bin/env python3
"""Build the inner pages from index.html.

The sprite, header, footer and quick bar are lifted straight out of index.html
so there is exactly one copy of each on the site: edit the homepage and every
page follows. Only the <main> content and the per-page metadata live here.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = "https://adaircondsolution.com/"

def read(name):
    with open(os.path.join(ROOT, name), encoding="utf-8") as fh:
        return fh.read()

home = read("index.html")

def between(start, end, src=home):
    i = src.index(start)
    j = src.index(end, i)
    return src[i:j + len(end)]

BUILD   = re.search(r'<meta name="build" content="([^"]+)">', home).group(1)
SPRITE  = between('<svg class="sprite"', '</svg>\n')
HEADER  = between('<header class="site-header"', '</header>\n')
SCRIM   = '<div class="nav-scrim" id="navScrim" hidden></div>\n'
FOOTER  = between('<footer class="footer">', '</footer>\n')
QUICK   = between('<div class="quickbar"', '</div>\n')
SCRIPT  = re.search(r'<script src="assets/js/main\.js[^"]*"[^>]*></script>', home).group(0)

BIZ = {
    "@type": "HVACBusiness",
    "name": "Ad Aircond Solution",
    "telephone": "+60178570744",
    "url": SITE,
}

def head(page):
    css = f'?v={BUILD}'
    ld = page.get("jsonld")
    ld_block = f'\n<script type="application/ld+json">\n{ld}\n</script>\n' if ld else ""
    return f'''<!DOCTYPE html>
<!-- BUILD {BUILD} · generated by build-pages.py — edit that file, not this one -->
<html lang="en-MY">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="build" content="{BUILD}">
<title>{page["title"]}</title>
<meta name="description" content="{page["description"]}">
<meta name="theme-color" content="#0c8a99">
<link rel="canonical" href="{SITE}{page["slug"]}">
<link rel="icon" href="favicon.svg" type="image/svg+xml">

<meta property="og:type" content="website">
<meta property="og:title" content="{page["title"]}">
<meta property="og:description" content="{page["description"]}">
<meta property="og:url" content="{SITE}{page["slug"]}">
<meta property="og:locale" content="en_MY">
<meta name="twitter:card" content="summary_large_image">

<link rel="preload" href="assets/fonts/inter-var-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="assets/fonts/poppins-600-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="assets/css/fonts.css{css}">
<link rel="stylesheet" href="assets/css/styles.css{css}">
</head>
<body>
{SPRITE}
{mark_active(HEADER, page["nav"])}
{SCRIM}
<main id="main">
{page["body"]}
</main>

{FOOTER}
{QUICK}{ld_block}
{SCRIPT}
</body>
</html>
'''

def mark_active(header, key):
    """Flag the nav item this page belongs to, whichever attribute order it uses."""
    header = header.replace('nav__link is-active', 'nav__link')  # clear the homepage's own
    def fix(m):
        tag = m.group(0).replace('class="nav__link', 'class="nav__link is-active', 1)
        return tag.replace('>', ' aria-current="page">', 1)
    return re.sub(r'<a[^>]*data-nav="%s"[^>]*>' % re.escape(key), fix, header, count=1)

def crumbs(*items):
    """BreadcrumbList JSON-LD from (name, slug) pairs."""
    el = ",\n".join(
        f'    {{"@type":"ListItem","position":{i+1},"name":"{n}","item":"{SITE}{s}"}}'
        for i, (n, s) in enumerate(items))
    return '{\n  "@context": "https://schema.org",\n  "@type": "BreadcrumbList",\n  "itemListElement": [\n' + el + '\n  ]\n}'

def service_ld(name, desc, slug):
    return ('{\n  "@context": "https://schema.org",\n  "@type": "Service",\n'
            f'  "name": "{name}",\n  "description": "{desc}",\n'
            '  "serviceType": "Air conditioning",\n'
            '  "provider": {\n    "@type": "HVACBusiness",\n    "name": "Ad Aircond Solution",\n'
            '    "telephone": "+60178570744",\n'
            '    "address": {\n      "@type": "PostalAddress",\n'
            '      "streetAddress": "14, Jalan Batu Bata, Titiwangsa Central",\n'
            '      "addressLocality": "Kuala Lumpur",\n      "postalCode": "50400",\n'
            '      "addressRegion": "Wilayah Persekutuan Kuala Lumpur",\n'
            '      "addressCountry": "MY"\n    }\n  },\n'
            '  "areaServed": { "@type": "City", "name": "Kuala Lumpur" },\n'
            f'  "url": "{SITE}{slug}"\n}}')

# --- content and entry point are appended below ---


# ---------------------------------------------------------------- components

def bc(*items):
    """Visible breadcrumb trail; the last item is the current page."""
    out = []
    for i, (name, href) in enumerate(items):
        if i == len(items) - 1:
            out.append(f'<li aria-current="page">{name}</li>')
        else:
            out.append(f'<li><a href="{href}">{name}</a></li>')
    return '<nav class="crumbs" aria-label="Breadcrumb"><ol>' + "".join(out) + "</ol></nav>"


def phero(kicker, title_a, title_b, lede, photo, crumb):
    return f'''<section class="phero">
  <span class="deco deco--photo deco--leaves-l" aria-hidden="true"></span>
  <div class="wrap phero__grid">
    <div class="phero__copy">
      {crumb}
      <p class="kicker">{kicker}</p>
      <h1 class="phero__title">{title_a} <em>{title_b}</em></h1>
      <p class="phero__lede">{lede}</p>
      <div class="phero__actions">
        <a class="btn btn--primary btn--lg" href="contact.html"><svg class="ico" aria-hidden="true"><use href="#i-calendar"></use></svg>Book a Service</a>
        <a class="btn btn--card btn--lg" href="tel:+60178570744"><svg class="ico" aria-hidden="true"><use href="#i-phone"></use></svg>+60178570744</a>
      </div>
    </div>
    <div class="phero__media"><span class="phero__photo" style="background-image:url(&quot;assets/img/{photo}&quot;)"></span></div>
  </div>
</section>'''


def checks(title, items):
    lis = "".join(
        '<li><span class="checks__ico"><svg class="ico" aria-hidden="true">'
        f'<use href="#i-check"></use></svg></span><span>{t}</span></li>' for t in items)
    return f'<div class="checks"><h3 class="checks__title">{title}</h3><ul class="checks__list">{lis}</ul></div>'


def article(heading, paras, aside=None):
    body = "".join(f"<p>{t}</p>" for t in paras)
    head_html = f'<h2 class="h2 h2--sm">{heading}</h2>'
    if aside:
        return f'''<section class="section">
  <div class="wrap prose__grid">
    <div class="prose">{head_html}{body}</div>
    <div class="prose__aside">{aside}</div>
  </div>
</section>'''
    return f'''<section class="section section--tight">
  <div class="wrap">
    <div class="prose prose--solo">{head_html}{body}</div>
  </div>
</section>'''


CTA = '''<section class="section callout-wrap">
  <div class="wrap">
    <div class="callout">
      <div class="callout__scene" aria-hidden="true"></div>
      <div class="callout__skyline" aria-hidden="true"></div>
      <div class="callout__body">
        <h2 class="h2 callout__title">Not sure what your unit needs?<em>Tell us what it is doing.</em></h2>
        <p class="callout__lede">Describe the symptom and we will confirm which service fits before anything is booked.</p>
        <div class="callout__actions">
          <a class="btn btn--white btn--lg" href="contact.html"><svg class="ico" aria-hidden="true"><use href="#i-calendar"></use></svg>Request a Service Visit</a>
          <a class="btn btn--glass btn--lg" href="https://wa.me/60178570744" target="_blank" rel="noopener"><svg class="ico" aria-hidden="true"><use href="#i-whatsapp"></use></svg>WhatsApp us</a>
        </div>
      </div>
    </div>
  </div>
</section>'''


# slug, name, sprite icon, photo, the .svc__media-- modifier the CSS defines
SERVICES = [
    ("ac-repair.html",             "AC Repair",             "i-tools",   "svc-repair.webp",       "repair"),
    ("ac-cleaning.html",           "AC Cleaning",           "i-wind",    "svc-cleaning.webp",     "cleaning"),
    ("ac-installation.html",       "AC Installation",       "i-cog",     "svc-installation.webp", "installation"),
    ("ac-maintenance.html",        "AC Maintenance",        "i-install", "svc-maintenance.webp",  "maintenance"),
    ("gas-refilling.html",         "Gas Refilling",         "i-snow",    "svc-gas.webp",          "gas"),
    ("ac-electrical-service.html", "AC Electrical Service", "i-bolt",    "svc-electrical.webp",   "electrical"),
]


def others(current):
    cards = "".join(f'''
      <a class="minicard" href="{slug}">
        <span class="minicard__icon"><svg class="ico" aria-hidden="true"><use href="#{icon}"></use></svg></span>
        <span class="minicard__name">{name}</span>
        <svg class="ico ico--sm minicard__go" aria-hidden="true"><use href="#i-arrow"></use></svg>
      </a>''' for slug, name, icon, _, _m in SERVICES if slug != current)
    return f'''<section class="section section--alt">
  <div class="wrap">
    <header class="sec-head sec-head--tight">
      <p class="pill">More services</p>
      <h2 class="h2 h2--sm">Everything else we look after</h2>
    </header>
    <div class="minigrid">{cards}
    </div>
  </div>
</section>'''


# ---------------------------------------------------------------------- pages

def service_page(slug, nav_name, kicker, title_a, title_b, lede, photo,
                 intro_h, intro_p, list_title, list_items,
                 second_h, second_p, meta_title, meta_desc):
    crumb = bc(("Home", "index.html"), ("Our Services", "services.html"), (nav_name, slug))
    body = "\n".join([
        phero(kicker, title_a, title_b, lede, photo, crumb),
        article(intro_h, intro_p, checks(list_title, list_items)),
        article(second_h, second_p),
        others(slug),
        CTA,
    ])
    return {
        "slug": slug, "nav": "services", "title": meta_title, "description": meta_desc,
        "body": body,
        # two graphs in one tag must be a JSON array, not two objects
        "jsonld": "[\n" + service_ld(nav_name, meta_desc, slug) + ",\n" + crumbs(
            ("Home", ""), ("Our Services", "services.html"), (nav_name, slug)) + "\n]",
    }


PAGES = []

PAGES.append(service_page(
    "ac-repair.html", "AC Repair", "AC Repair",
    "Aircond repair,", "diagnosed before it is fixed",
    "A unit that has stopped cooling, stopped starting or failed mid-use gets inspected first, so the repair answers the actual fault rather than the symptom.",
    "svc-repair.webp",
    "What an aircond repair visit involves",
    ["Weak cooling, no cooling and a unit that will not start all have several possible causes. A dirty coil, a failing capacitor, a blocked drain line, a refrigerant leak and a control fault can each produce the same complaint, and each needs a different fix.",
     "So the visit begins with an inspection: the technician checks how the unit is behaving, works back to the component responsible, and explains what was found before any part is replaced. You hear what is wrong and what putting it right involves.",
     "Where a repair is not the sensible answer &mdash; an old unit with a failing compressor, for instance &mdash; we will say so rather than sell you a repair that will not last."],
    "Faults we are called out for",
    ["Unit runs but the room does not get cold", "Unit will not switch on or trips the breaker",
     "Water dripping from the indoor unit", "Ice forming on the coil or pipework",
     "Loud rattling, grinding or buzzing", "Unit short-cycles or shuts off by itself",
     "Remote or control board not responding", "Burning or musty smell when running"],
    "Repairs for homes and business premises",
    ["We work on wall-mounted splits in homes and apartments, and on the units keeping offices, shops and other commercial premises trading. For a business, downtime matters, so tell us your opening hours when you book and we will work around them.",
     "Parts are matched to your system. If a component needs ordering, you will be told what it is and how long it takes before we proceed."],
    "AC Repair in Kuala Lumpur | Ad Aircond Solution",
    "Aircond repair in Kuala Lumpur for units that have stopped cooling, will not start, leak water or trip the breaker. Inspection first, then the fix. Call +60178570744."))

PAGES.append(service_page(
    "ac-cleaning.html", "AC Cleaning", "AC Cleaning",
    "Deep cleaning that", "restores airflow",
    "Filters, coils, the blower wheel and the drain line are cleaned properly, so the unit moves the air it was built to move and sheds heat the way it should.",
    "svc-cleaning.webp",
    "Why cleaning changes how a unit performs",
    ["Dust loads up quickly in Kuala Lumpur. It settles on the filter first, then works through to the coil and the blower wheel, and as it builds the unit has to run longer to reach the same temperature.",
     "A clogged coil cannot shed heat properly and a coated blower wheel cannot push air. That shows up as weak cooling and a longer running time, and it is why a unit that is only a couple of years old can feel like it has lost its edge.",
     "Cleaning also clears the drain line. A blocked drain is the usual reason water ends up marking a wall, and it is far cheaper to clear than to repair the damage it causes."],
    "What gets cleaned",
    ["Filters washed and refitted", "Indoor coil cleaned down", "Blower wheel cleared of build-up",
     "Drain line flushed and checked", "Drain pan cleaned out", "Outdoor coil and fan cleaned",
     "Casing and louvres wiped down", "Cooling checked before we leave"],
    "How often it is worth doing",
    ["How often depends on the room rather than the calendar. A unit running most of the day, a home near a busy road, a kitchen, a shop floor or a household with pets will load up faster than a bedroom used only at night.",
     "We will tell you what the filters and coil actually looked like at this visit, so you can judge the right interval for your own space instead of guessing."],
    "AC Cleaning &amp; Servicing in Kuala Lumpur | Ad Aircond Solution",
    "Aircond cleaning in Kuala Lumpur: filters, coil, blower wheel and drain line cleaned so airflow and cooling come back. Call +60178570744."))

PAGES.append(service_page(
    "ac-installation.html", "AC Installation", "AC Installation",
    "Installation done", "properly the first time",
    "Mounting, piping, drainage, electrical connection and commissioning &mdash; set up so the system performs as it was designed to from the day it is switched on.",
    "svc-installation.webp",
    "What a proper installation covers",
    ["How well an air conditioner performs has as much to do with how it was fitted as with the unit itself. Bracket placement, pipe run length, the fall on the drain line and the electrical connection all decide whether you get the cooling you paid for.",
     "We site the indoor unit where the air will actually reach the room, run the pipework and drain with the right fall, make the electrical connection safely, then commission the system and check it is cooling as it should before we leave.",
     "If you are still choosing a unit, tell us the room size and how it is used. We will tell you what capacity suits it &mdash; oversizing costs more to run and cools less comfortably than people expect."],
    "Included in an installation",
    ["Site check before the quote", "Indoor unit mounted and levelled",
     "Refrigerant pipework run and insulated", "Drain line run with correct fall",
     "Outdoor unit sited and secured", "Electrical connection made safely",
     "System vacuumed and commissioned", "Cooling verified before handover"],
    "Replacements and additional units",
    ["Replacing an old unit is often simpler than a first installation, because the pipe run and drain may be reusable. We check their condition first rather than assuming, since reusing a pipe run in poor condition causes problems later.",
     "Adding a unit to a home or premises that already has one is straightforward. Tell us where it needs to go and we will confirm what the run involves."],
    "AC Installation in Kuala Lumpur | Ad Aircond Solution",
    "Air conditioner installation in Kuala Lumpur: mounting, pipework, drainage, electrical connection and commissioning. Call +60178570744."))

PAGES.append(service_page(
    "ac-maintenance.html", "AC Maintenance", "AC Maintenance",
    "Maintenance that", "catches faults early",
    "Scheduled visits that keep a system running at its best and flag small issues while they are still small jobs.",
    "svc-maintenance.webp",
    "What maintenance is for",
    ["Most air conditioner failures announce themselves before they happen. A capacitor on its way out, a drain starting to block, a coil losing its ability to shed heat &mdash; each shows up as a change in how the unit behaves well before it stops.",
     "A maintenance visit is where those get noticed. The unit is cleaned, its operation checked, and anything heading for a problem is flagged while it is still cheap to deal with.",
     "The other half of it is running cost. A system kept clean reaches temperature sooner and runs for less time to hold it, which is the difference you feel on the bill rather than in the room."],
    "Covered at each visit",
    ["Filters and coil cleaned", "Drain line checked and flushed",
     "Airflow and cooling performance checked", "Refrigerant pressure checked",
     "Electrical connections inspected", "Fan and blower operation checked",
     "Outdoor unit cleaned and inspected", "Written note of anything to watch"],
    "Scheduled cover for premises with several units",
    ["Offices, shops and other premises running several units are easier to look after on a schedule than one call-out at a time. Units get attended in one visit, and you get a single picture of which ones are fine and which need attention.",
     "Tell us how many units you have and where they are, and we will set out what a visit covers and how often it is worth doing for your site."],
    "AC Maintenance in Kuala Lumpur | Ad Aircond Solution",
    "Scheduled aircond maintenance in Kuala Lumpur for homes and business premises. Cleaning, checks and early warning of faults. Call +60178570744."))

PAGES.append(service_page(
    "gas-refilling.html", "Gas Refilling", "Gas Refilling",
    "Refrigerant checked,", "then topped up",
    "Weak cooling often means low refrigerant. We check the system for the leak that caused it before refilling, so the gas stays in.",
    "svc-gas.webp",
    "Why we look for the leak first",
    ["Refrigerant is not consumed. A sealed system holds the same charge for years, so if the level has dropped it has escaped somewhere &mdash; a joint, a flare, a pipe run or the coil itself.",
     "Refilling without finding that leak means paying for gas twice: the cooling comes back for a while, then fades again as the charge escapes the same way it did the first time.",
     "So the visit starts with pressure readings and a leak check. If we find one, you are told where it is and what repairing it involves, and the system is refilled once it will hold the charge."],
    "Signs the charge may be low",
    ["Cooling has faded gradually over weeks", "Unit runs constantly without reaching temperature",
     "Ice forming on the pipework or coil", "Air from the vents is cool but not cold",
     "Hissing or bubbling from the indoor unit", "Higher electricity use with no change in habits",
     "Oily residue near pipe joints", "Cooling is worse on the hottest days"],
    "The right gas for your system",
    ["Different systems take different refrigerants, and they are not interchangeable. We identify what your unit is charged with and refill with that, to the pressure the manufacturer specifies rather than by feel.",
     "If the readings show the problem is not refrigerant at all &mdash; a dirty coil and a low charge can feel identical from the room &mdash; we will tell you that instead of selling you gas you do not need."],
    "Aircond Gas Refilling in Kuala Lumpur | Ad Aircond Solution",
    "Aircond gas refilling in Kuala Lumpur. Leak check and pressure test first, then refilled with the correct refrigerant. Call +60178570744."))

PAGES.append(service_page(
    "ac-electrical-service.html", "AC Electrical Service", "AC Electrical Service",
    "Electrical faults", "traced and handled safely",
    "From a failed capacitor to wiring and control faults &mdash; the electrical side of an air conditioner, diagnosed and repaired properly.",
    "svc-electrical.webp",
    "The electrical faults behind common symptoms",
    ["A unit that will not start, starts and stops, hums without running or trips the breaker is usually an electrical problem rather than a cooling one. Capacitors, contactors, fan motors, control boards and the wiring between them are all candidates.",
     "These are the faults where guessing is expensive. Replacing a control board when the capacitor was the problem costs several times what the actual fix would have. So the fault is traced to the component before anything is replaced.",
     "This is also the part of an air conditioner where working on it yourself is genuinely dangerous. Capacitors hold a charge after the power is off, and a unit that is tripping a breaker is telling you something that should not be reset and ignored."],
    "Electrical work we carry out",
    ["Capacitor testing and replacement", "Contactor and relay faults",
     "Fan and blower motor faults", "Control board diagnosis",
     "Wiring and terminal faults", "Units tripping the breaker",
     "Remote and sensor faults", "Power supply checks at the unit"],
    "When a breaker keeps tripping",
    ["A breaker that trips when the air conditioner runs is doing its job &mdash; something in the circuit is drawing more current than it should. Resetting it repeatedly does not fix the cause and is not safe.",
     "Switch the unit off at the isolator and call us. We will find what is drawing the current, whether that is the unit, its wiring or the supply, and put it right."],
    "AC Electrical Service in Kuala Lumpur | Ad Aircond Solution",
    "Aircond electrical repair in Kuala Lumpur: capacitors, wiring, control boards and units tripping the breaker. Call +60178570744."))


# --- services hub -----------------------------------------------------------

_svc_cards = "".join(f'''
      <a class="svc svc--link" href="{slug}">
        <span class="svc__media svc__media--{mod}"></span>
        <span class="svc__badge"><svg class="ico" aria-hidden="true"><use href="#{icon}"></use></svg></span>
        <span class="svc__body">
          <span class="svc__title">{name}</span>
          <span class="svc__rule" aria-hidden="true"></span>
          <span class="svc__go">View service<svg class="ico ico--sm" aria-hidden="true"><use href="#i-arrow"></use></svg></span>
        </span>
      </a>''' for slug, name, icon, _, mod in SERVICES)

PAGES.append({
    "slug": "services.html", "nav": "services",
    "title": "Our Services | Aircond Repair, Cleaning &amp; Installation in Kuala Lumpur",
    "description": "The six air conditioning services Ad Aircond Solution provides in Kuala Lumpur: repair, cleaning, installation, maintenance, gas refilling and electrical work.",
    "body": "\n".join([
        phero("Our Services", "Complete AC care,", "all in one place",
              "Repair, cleaning, installation, maintenance, gas refilling and electrical work &mdash; for homes and business premises across Kuala Lumpur.",
              "svc-installation.webp",
              bc(("Home", "index.html"), ("Our Services", "services.html"))),
        f'''<section class="section services">
  <div class="wrap">
    <header class="sec-head services__head">
      <h2 class="h2 services__title">Six services, <em>one team</em></h2>
      <span class="rule-ico" aria-hidden="true"><i class="rule-ico__line"></i><svg class="ico" aria-hidden="true"><use href="#i-snow"></use></svg><i class="rule-ico__line"></i></span>
      <p class="sec-head__text">Whichever one you need, the visit starts the same way &mdash; we look at the unit before recommending anything.</p>
    </header>
    <div class="svc-grid">{_svc_cards}
    </div>
  </div>
</section>''',
        article("Not sure which one you need?", [
            "Most people call about a symptom rather than a service, and that is the right way round. Weak cooling can be a dirty coil, a low refrigerant charge or a failing capacitor, and those are three different jobs.",
            "Tell us what the unit is doing &mdash; how it sounds, when it started, whether it cools at all &mdash; and we will tell you which service fits before anything is booked. If it turns out to be the cheaper job, that is the one we will quote."]),
        CTA,
    ]),
    "jsonld": crumbs(("Home", ""), ("Our Services", "services.html")),
})


# --- about ------------------------------------------------------------------

def _pull(start, end):
    """Reuse a block that already exists on the homepage."""
    return between(start, end)

PAGES.append({
    "slug": "about.html", "nav": "about",
    "title": "About Us | Ad Aircond Solution, Kuala Lumpur",
    "description": "Ad Aircond Solution provides air conditioning repair, servicing, maintenance and installation for homes and businesses across Kuala Lumpur. Based at Titiwangsa Central.",
    "body": "\n".join([
        phero("About Us", "Built on service.", "Driven by comfort.",
              "Air conditioning repair, servicing, maintenance and installation for homes and businesses across Kuala Lumpur, from a workshop at Titiwangsa Central.",
              "about.webp",
              bc(("Home", "index.html"), ("About Us", "about.html"))),
        _pull('<!-- ============ ABOUT US ============ -->', '</section>\n'),
        article("How we work", [
            "Every job starts with looking at the unit. A room that is not getting cold can point to a dirty coil, a blocked drain, a low refrigerant charge, a failing capacitor or a control fault, and the only way to know which is to inspect rather than assume.",
            "What we find gets explained in plain terms &mdash; what is wrong, what fixing it involves, and what it will take. If a repair is not worth doing on an old unit, we will say so.",
            "The work itself gets the same care as the diagnosis: the unit is left working properly, and the room is left as we found it."],
            checks("What you can expect", [
                "The unit inspected before anything is quoted",
                "The fault explained in plain language",
                "Parts matched to your system",
                "Work carried out at the agreed time",
                "The space left clean afterwards",
                "A straight answer when a repair is not worth it"])),
        CTA,
    ]),
    "jsonld": crumbs(("Home", ""), ("About Us", "about.html")),
})


# --- contact ----------------------------------------------------------------

PAGES.append({
    "slug": "contact.html", "nav": "contact",
    "title": "Contact | Ad Aircond Solution, Kuala Lumpur",
    "description": "Call or WhatsApp Ad Aircond Solution on +60178570744, or send your details through the form. 14, Jalan Batu Bata, Titiwangsa Central, 50400 Kuala Lumpur.",
    "body": "\n".join([
        phero("Contact", "Tell us what", "your aircond is doing",
              "Call, WhatsApp, or send the details through the form and we will confirm the service and a time that suits you.",
              "step-contact.webp",
              bc(("Home", "index.html"), ("Contact", "contact.html"))),
        _pull('<!-- ============ FINAL CTA + BOOKING ============ -->', '</section>\n'),
    ]),
    "jsonld": crumbs(("Home", ""), ("Contact", "contact.html")),
})


if __name__ == "__main__":
    for page in PAGES:
        out = head(page)
        with open(os.path.join(ROOT, page["slug"]), "w", encoding="utf-8") as fh:
            fh.write(out)
        print(f'{page["slug"]:30s} {len(out) // 1024:>3} KB')
    print(f"{len(PAGES)} pages built from index.html")
