#!/usr/bin/env python3
"""Build the inner pages from index.html.

The sprite, header, footer and quick bar are lifted straight out of index.html
so there is exactly one copy of each on the site: edit the homepage and every
page follows. Only the <main> content and the per-page metadata live here.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = "https://adaircondsolution.com/"

def read(name):
    with open(os.path.join(ROOT, name), encoding="utf-8") as fh:
        return fh.read()

home = read("index.html")

def between(start, end, src=home):
    i = src.index(start)
    j = src.index(end, i)
    return src[i:j + len(end)]

BUILD   = re.search(r'<meta name="build" content="([^"]+)">', home).group(1)
SPRITE  = between('<svg class="sprite"', '</svg>\n')
HEADER  = between('<header class="site-header"', '</header>\n')
SCRIM   = '<div class="nav-scrim" id="navScrim" hidden></div>\n'
FOOTER  = between('<footer class="footer">', '</footer>\n')
QUICK   = between('<div class="quickbar"', '</div>\n')
SCRIPT  = re.search(r'<script src="/assets/js/main\.js[^"]*"[^>]*></script>', home).group(0)

BIZ = {
    "@type": "HVACBusiness",
    "name": "Ad Aircond Solution",
    "telephone": "+60178570744",
    "url": SITE,
}

def head(page):
    css = f'?v={BUILD}'
    ld = page.get("jsonld")
    ld_block = f'\n<script type="application/ld+json">\n{ld}\n</script>\n' if ld else ""
    return f'''<!DOCTYPE html>
<!-- BUILD {BUILD} · generated by build-pages.py — edit that file, not this one -->
<html lang="en-MY">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="build" content="{BUILD}">
<title>{page["title"]}</title>
<meta name="description" content="{page["description"]}">
<meta name="theme-color" content="#0c8a99">
<link rel="canonical" href="{SITE}{page["url"]}">
<link rel="icon" href="/favicon.ico" sizes="48x48">
<link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32">
<link rel="icon" href="/icon-192.png" type="image/png" sizes="192x192">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">

<meta property="og:type" content="website">
<meta property="og:title" content="{page["title"]}">
<meta property="og:description" content="{page["description"]}">
<meta property="og:url" content="{SITE}{page["url"]}">
<meta property="og:site_name" content="Ad Aircond Solution">
<meta property="og:image" content="{SITE}assets/img/{page["image"]}">
<meta property="og:locale" content="en_MY">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="{SITE}assets/img/{page["image"]}">

<link rel="preload" href="/assets/fonts/inter-var-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/poppins-600-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/assets/css/fonts.css{css}">
<link rel="stylesheet" href="/assets/css/styles.css{css}">
</head>
<body>
{SPRITE}
{mark_active(HEADER, page["nav"])}
{SCRIM}
<main id="main">
{page["body"]}
</main>

{FOOTER}
{QUICK}{ld_block}
{SCRIPT}
</body>
</html>
'''

def mark_active(header, key):
    """Flag the nav item this page belongs to, whichever attribute order it uses."""
    header = header.replace('nav__link is-active', 'nav__link')  # clear the homepage's own
    def fix(m):
        tag = m.group(0).replace('class="nav__link', 'class="nav__link is-active', 1)
        return tag.replace('>', ' aria-current="page">', 1)
    return re.sub(r'<a[^>]*data-nav="%s"[^>]*>' % re.escape(key), fix, header, count=1)

def crumbs(*items):
    """BreadcrumbList JSON-LD from (name, slug) pairs."""
    el = ",\n".join(
        f'    {{"@type":"ListItem","position":{i+1},"name":"{n}","item":"{SITE}{s}"}}'
        for i, (n, s) in enumerate(items))
    return '{\n  "@context": "https://schema.org",\n  "@type": "BreadcrumbList",\n  "itemListElement": [\n' + el + '\n  ]\n}'

def service_ld(name, desc, slug):
    return ('{\n  "@context": "https://schema.org",\n  "@type": "Service",\n'
            f'  "name": "{name}",\n  "description": "{desc}",\n'
            '  "serviceType": "Air conditioning",\n'
            '  "provider": {\n    "@type": "HVACBusiness",\n    "name": "Ad Aircond Solution",\n'
            '    "telephone": "+60178570744",\n'
            '    "address": {\n      "@type": "PostalAddress",\n'
            '      "streetAddress": "14, Jalan Batu Bata, Titiwangsa Central",\n'
            '      "addressLocality": "Kuala Lumpur",\n      "postalCode": "50400",\n'
            '      "addressRegion": "Wilayah Persekutuan Kuala Lumpur",\n'
            '      "addressCountry": "MY"\n    }\n  },\n'
            '  "areaServed": { "@type": "City", "name": "Kuala Lumpur" },\n'
            f'  "url": "{SITE}{slug}"\n}}')

# --- content and entry point are appended below ---


# ---------------------------------------------------------------- components

def drop(html, start, end):
    """Remove one block from a chunk of markup, from start to the end marker."""
    i = html.index(start)
    j = html.index(end, i) + len(end)
    return html[:i] + html[j:]


def bc(*items):
    """Visible breadcrumb trail; an item with no href is the current page."""
    out = [f'<li aria-current="page">{n}</li>' if h is None else f'<li><a href="{h}">{n}</a></li>'
           for n, h in items]
    return '<nav class="crumbs" aria-label="Breadcrumb"><ol>' + "".join(out) + "</ol></nav>"


def checks(title, items):
    lis = "".join(
        '<li><span class="checks__ico"><svg class="ico" aria-hidden="true">'
        f'<use href="#i-check"></use></svg></span><span>{t}</span></li>' for t in items)
    return f'<div class="checks"><h3 class="checks__title">{title}</h3><ul class="checks__list">{lis}</ul></div>'


def article(heading, paras, aside=None):
    body = "".join(f"<p>{t}</p>" for t in paras)
    head_html = f'<h2 class="h2 h2--sm">{heading}</h2>'
    if aside:
        return f'''<section class="section">
  <div class="wrap prose__grid">
    <div class="prose">{head_html}{body}</div>
    <div class="prose__aside">{aside}</div>
  </div>
</section>'''
    return f'''<section class="section section--tight">
  <div class="wrap">
    <div class="prose prose--solo">{head_html}{body}</div>
  </div>
</section>'''


CTA = '''<section class="section callout-wrap">
  <div class="wrap">
    <div class="callout">
      <div class="callout__scene" aria-hidden="true"></div>
      <div class="callout__skyline" aria-hidden="true"></div>
      <div class="callout__body">
        <h2 class="h2 callout__title">Not sure what your unit needs?<em>Tell us what it is doing.</em></h2>
        <p class="callout__lede">Describe the symptom and we will confirm which service fits before anything is booked.</p>
        <div class="callout__actions">
          <a class="btn btn--white btn--lg" href="/contact/"><svg class="ico" aria-hidden="true"><use href="#i-calendar"></use></svg>Request a Service Visit</a>
          <a class="btn btn--glass btn--lg" href="https://wa.me/60178570744" target="_blank" rel="noopener"><svg class="ico" aria-hidden="true"><use href="#i-whatsapp"></use></svg>WhatsApp us</a>
        </div>
      </div>
    </div>
  </div>
</section>'''


# directory, name, sprite icon, photo, the .svc__media-- modifier the CSS defines
SERVICES = [
    ("ac-repair",             "Aircond Repair",             "i-tools",   "svc-repair.webp",       "repair"),
    ("ac-cleaning",           "Aircond Cleaning",           "i-wind",    "svc-cleaning.webp",     "cleaning"),
    ("ac-installation",       "Aircond Installation",       "i-cog",     "svc-installation.webp", "installation"),
    ("ac-maintenance",        "Aircond Maintenance",        "i-install", "svc-maintenance.webp",  "maintenance"),
    ("gas-refilling",         "Gas Refilling",         "i-snow",    "svc-gas.webp",          "gas"),
    ("ac-electrical-service", "Aircond Electrical Service", "i-bolt",    "svc-electrical.webp",   "electrical"),
]


def others(current):
    cards = "".join(f'''
      <a class="minicard" href="/{slug}/">
        <span class="minicard__icon"><svg class="ico" aria-hidden="true"><use href="#{icon}"></use></svg></span>
        <span class="minicard__name">{name}</span>
        <svg class="ico ico--sm minicard__go" aria-hidden="true"><use href="#i-arrow"></use></svg>
      </a>''' for slug, name, icon, _, _m in SERVICES if slug != current)
    return f'''<section class="section section--alt">
  <div class="wrap">
    <header class="sec-head sec-head--tight">
      <p class="pill">More services</p>
      <h2 class="h2 h2--sm">Everything else we look after</h2>
    </header>
    <div class="minigrid">{cards}
    </div>
  </div>
</section>'''


# ------------------------------------------------------------------ about page

def ahero(kicker, line_a, line_b, lede, photo, crumb):
    """The standard page hero: homepage styling, no form and no cards.

    The photograph is set here rather than in the stylesheet because a url()
    written into a custom property resolves against the stylesheet, not the
    page — so each page can carry its own image.
    """
    return f'''<section class="ahero">
  <span class="ahero__photo" aria-hidden="true" style="background-image:url(&quot;/assets/img/{photo}&quot;)"></span>
  <div class="wrap ahero__inner">
    <p class="tagpill"><span class="tagpill__dot"></span>{kicker}</p>
    <h1 class="ahero__title">{line_a}<em>{line_b}</em></h1>
    <p class="ahero__lede">{lede}</p>
    <div class="ahero__actions">
      <a class="btn btn--primary btn--lg" href="/contact/"><svg class="ico" aria-hidden="true"><use href="#i-calendar"></use></svg>Book a Service</a>
      <a class="btn btn--card btn--lg" href="tel:+60178570744"><svg class="ico" aria-hidden="true"><use href="#i-phone"></use></svg>+60178570744</a>
    </div>
    {crumb}
  </div>
  <svg class="ahero__wave" viewBox="0 0 1440 90" preserveAspectRatio="none" aria-hidden="true" focusable="false">
    <path d="M0 46c220 44 460 44 720 12s500-44 720-12v44H0z" fill="#ffffff"/>
  </svg>
</section>'''


def vision_mission():
    return '''<section class="section vm">
  <span class="deco deco--photo deco--leaves-l" aria-hidden="true"></span>
  <div class="wrap">
    <header class="sec-head reveal">
      <p class="pill">What drives us</p>
      <h2 class="h2 vm__title">Vision and <em>mission</em></h2>
      <span class="rule-ico" aria-hidden="true"><i class="rule-ico__line"></i><svg class="ico" aria-hidden="true"><use href="#i-snow"></use></svg><i class="rule-ico__line"></i></span>
    </header>
    <div class="vm__grid">
      <article class="vm__card reveal">
        <span class="vm__icon"><svg class="ico" aria-hidden="true"><use href="#i-target"></use></svg></span>
        <h3 class="vm__name">Our Vision</h3>
        <p class="vm__text">To be the air-conditioning company people in Kuala Lumpur call first &mdash; known less for how loudly we advertise than for the fact that what we fix stays fixed.</p>
      </article>
      <article class="vm__card vm__card--accent reveal" data-delay="1">
        <span class="vm__icon"><svg class="ico" aria-hidden="true"><use href="#i-heart"></use></svg></span>
        <h3 class="vm__name">Our Mission</h3>
        <p class="vm__text">To diagnose before we repair, explain before we invoice, and leave every home and business cooler than we found it &mdash; with work our technicians would be happy to put their own name to.</p>
      </article>
    </div>
  </div>
</section>'''


def journey():
    steps = [
        ("Where it started", "Ad Aircond Solution began the way most trades do &mdash; one technician, a van, and the units in the neighbourhood around Titiwangsa Central."),
        ("Word got around", "Repeat calls turned into referrals. Households that had been told to replace a unit found it could be repaired, and told their neighbours."),
        ("Homes, then premises", "Offices, shops and other business premises came next, where a unit going down costs trading hours and the work has to fit around opening times."),
        ("Where we are now", "A workshop at Titiwangsa Central, a team working across Kuala Lumpur, and the same rule we started with: look at the unit before recommending anything."),
    ]
    items = "".join(f'''
      <li class="tl__item reveal" data-delay="{i}">
        <span class="tl__dot" aria-hidden="true"></span>
        <div class="tl__card">
          <h3 class="tl__name">{n}</h3>
          <p class="tl__text">{t}</p>
        </div>
      </li>''' for i, (n, t) in enumerate(steps))
    return f'''<section class="section section--alt journey">
  <div class="wrap">
    <header class="sec-head reveal">
      <p class="pill">Our journey</p>
      <h2 class="h2 journey__title">How the business <em>grew</em></h2>
      <p class="sec-head__text">No overnight story &mdash; just work that led to the next job.</p>
    </header>
    <ol class="tl">{items}
    </ol>
  </div>
</section>'''


def numbers():
    """Figures the business supplied. Each is marked so it can be checked."""
    stats = [
        ("i-badge",  "Certified",      "technicians",        "Trained on the systems they work on"),
        ("i-grid",   "All major",      "brands &amp; models","Daikin, Panasonic, Mitsubishi, LG and more"),
        ("i-pin",    "KL &amp; Selangor", "coverage",        "Based at Titiwangsa Central"),
        ("i-tools",  "50+",            "vehicles on the road","So a technician is never far away"),
    ]
    cards = "".join(f'''
      <li class="stat reveal" data-delay="{i}">
        <span class="stat__icon"><svg class="ico" aria-hidden="true"><use href="#{ic}"></use></svg></span>
        <p class="stat__num">{a}</p>
        <p class="stat__label">{b}</p>
        <p class="stat__note">{note}</p>
      </li>''' for i, (ic, a, b, note) in enumerate(stats))
    return f'''<!-- FIGURES TO CONFIRM: "Certified", "KL & Selangor" and "50+ vehicles"
     were supplied by the business and have not been verified here. Correct or
     remove any that are not accurate before launch. -->
<section class="section stats">
  <span class="deco deco--photo deco--unit-r" aria-hidden="true"></span>
  <div class="wrap">
    <header class="sec-head reveal">
      <p class="pill">At a glance</p>
      <h2 class="h2 stats__title">What we bring <em>to every job</em></h2>
      <span class="rule-ico" aria-hidden="true"><i class="rule-ico__line"></i><svg class="ico" aria-hidden="true"><use href="#i-snow"></use></svg><i class="rule-ico__line"></i></span>
    </header>
    <ul class="stats__grid">{cards}
    </ul>
  </div>
</section>'''


def team():
    roles = [
        ("i-user",    "Service technicians", "On the tools every day &mdash; inspection, repair, cleaning and installation across homes and business premises."),
        ("i-headset", "Booking &amp; coordination", "The people who take your call, work out which service fits, and set a time that suits the household or the business."),
        ("i-cog",     "Installation crew",   "Mounting, pipework, drainage and commissioning &mdash; the part that decides how well a new system performs."),
    ]
    cards = "".join(f'''
      <article class="tm reveal" data-delay="{i}">
        <span class="tm__icon"><svg class="ico" aria-hidden="true"><use href="#{ic}"></use></svg></span>
        <h3 class="tm__name">{n}</h3>
        <p class="tm__text">{t}</p>
      </article>''' for i, (ic, n, t) in enumerate(roles))
    return f'''<!-- TEAM: no names or photographs have been invented. Send real names,
     roles and permission-cleared photographs and they can replace these role
     cards. -->
<section class="section section--alt teamsec">
  <div class="wrap">
    <header class="sec-head reveal">
      <p class="pill">Our team</p>
      <h2 class="h2 teamsec__title">The people who <em>do the work</em></h2>
      <p class="sec-head__text">Small enough that the person who takes your call knows the technician who turns up.</p>
    </header>
    <div class="tm-grid">{cards}
    </div>
  </div>
</section>'''


def capability():
    items = [
        ("i-grid",   "Every model and brand",
         "Wall-mounted splits, ceiling cassettes and outdoor condensers &mdash; Daikin, Panasonic, Mitsubishi Electric, LG, Samsung, York, Midea and the rest. Tell us the make and model and we will confirm before booking."),
        ("i-badge",  "Trained technicians",
         "The people who arrive work on these systems daily. They are trained on the equipment they are sent to, not handed a job they have never seen."),
        ("i-shield", "Safe electrical work",
         "Capacitors, wiring and control boards are the part of an air conditioner where guessing is both expensive and dangerous. That work is traced to the component and handled properly."),
        ("i-clock",  "Around your hours",
         "Households get a time that suits them. Business premises get a visit that fits around trading hours, because a shop cannot close for an aircond."),
    ]
    cards = "".join(f'''
      <article class="cap reveal" data-delay="{i}">
        <span class="cap__icon"><svg class="ico" aria-hidden="true"><use href="#{ic}"></use></svg></span>
        <div class="cap__body">
          <h3 class="cap__name">{n}</h3>
          <p class="cap__text">{t}</p>
        </div>
      </article>''' for i, (ic, n, t) in enumerate(items))
    return f'''<section class="section capsec">
  <div class="wrap">
    <header class="sec-head reveal">
      <p class="pill">What we handle</p>
      <h2 class="h2 capsec__title">Whatever the unit, <em>whoever made it</em></h2>
      <p class="sec-head__text">The equipment changes from job to job. The way we approach it does not.</p>
    </header>
    <div class="cap-grid">{cards}
    </div>
  </div>
</section>'''


def problems():
    """Every service listed with the faults it covers, so a visitor who knows
    the symptom but not the service name can still find the right page."""
    rows = [
        ("ac-repair", "Aircond Repair", "i-tools", [
            "Unit runs but the room does not get cold",
            "Unit will not switch on, or trips the breaker",
            "Water dripping from the indoor unit",
            "Ice forming on the coil or the pipework",
            "Loud rattling, grinding or buzzing",
            "Unit short-cycles or shuts off by itself",
            "Remote or control board not responding",
            "Burning or musty smell when running"]),
        ("ac-cleaning", "Aircond Cleaning", "i-wind", [
            "Weak airflow from the vents",
            "Dusty or musty smell when the unit starts",
            "Filters clogged and grey with dust",
            "Coil coated and unable to shed heat",
            "Blower wheel packed with build-up",
            "Water marking the wall from a blocked drain",
            "Unit running far longer to reach temperature",
            "Mould or slime in the drain pan"]),
        ("ac-installation", "Aircond Installation", "i-cog", [
            "First installation in a new home or premises",
            "Replacing a unit that is beyond repair",
            "Adding a unit to a room that has none",
            "Relocating a unit to another wall or room",
            "Pipe run or drain that was never fitted properly",
            "Outdoor unit sited where it cannot breathe",
            "Drain that falls the wrong way and backs up",
            "Choosing the right capacity for the room"]),
        ("ac-maintenance", "Aircond Maintenance", "i-install", [
            "No service since the unit was installed",
            "Cooling that has quietly dropped off over months",
            "Electricity bill climbing with no change in use",
            "Several units on one premises to keep running",
            "Rental or shop units that cannot afford downtime",
            "Small faults you would rather catch early",
            "Refrigerant pressure never checked",
            "Electrical connections never inspected"]),
        ("gas-refilling", "Gas Refilling", "i-snow", [
            "Cooling faded gradually over weeks",
            "Unit runs constantly without reaching temperature",
            "Air from the vents is cool but never cold",
            "Ice on the pipework or the coil",
            "Hissing or bubbling from the indoor unit",
            "Oily residue near a pipe joint",
            "Cooling worst on the hottest days",
            "Refrigerant topped up before and lost again"]),
        ("ac-electrical-service", "Aircond Electrical Service", "i-bolt", [
            "Unit hums but the fan will not turn",
            "Breaker trips whenever the unit runs",
            "Unit starts then stops after a few seconds",
            "Capacitor swollen or failed",
            "Contactor chattering or burnt",
            "Fan or blower motor not running",
            "Control board or sensor faults",
            "Scorched wiring or terminals at the unit"]),
    ]
    cards = "".join(f'''
      <article class="plist reveal" data-delay="{i % 3}">
        <header class="plist__head">
          <span class="plist__icon"><svg class="ico" aria-hidden="true"><use href="#{ic}"></use></svg></span>
          <h3 class="plist__name">{name}</h3>
        </header>
        <ul class="plist__items">{"".join(f'<li>{t}</li>' for t in faults)}</ul>
        <a class="plist__go" href="/{slug}/">See {name}<svg class="ico ico--sm" aria-hidden="true"><use href="#i-arrow"></use></svg></a>
      </article>''' for i, (slug, name, ic, faults) in enumerate(rows))
    return f'''<section class="section section--alt problems">
  <div class="wrap">
    <header class="sec-head">
      <p class="pill">What we repair</p>
      <h2 class="h2 problems__title">The problems <em>we fix</em></h2>
      <span class="rule-ico" aria-hidden="true"><i class="rule-ico__line"></i><svg class="ico" aria-hidden="true"><use href="#i-snow"></use></svg><i class="rule-ico__line"></i></span>
      <p class="sec-head__text">If your unit is doing any of these, it is on our list. Find the symptom and it tells you which service you need.</p>
    </header>
    <div class="plist-grid">{cards}
    </div>
  </div>
</section>'''


# ---------------------------------------------------------------------- pages

def service_page(slug, nav_name, kicker, title_a, title_b, lede, photo,
                 intro_h, intro_p, list_title, list_items,
                 second_h, second_p, meta_title, meta_desc):
    url = f"{slug}/"
    crumb = bc(("Home", "/"), ("Our Services", "/services/"), (nav_name, None))
    body = "\n".join([
        ahero(kicker, title_a, title_b, lede, photo, crumb),
        article(intro_h, intro_p, checks(list_title, list_items)),
        article(second_h, second_p),
        others(slug),
        CTA,
    ])
    return {
        "dir": slug, "url": url, "nav": "services", "image": photo,
        "title": meta_title, "description": meta_desc, "body": body,
        # two graphs in one tag must be a JSON array, not two objects
        "jsonld": "[\n" + service_ld(nav_name, meta_desc, url) + ",\n" + crumbs(
            ("Home", ""), ("Our Services", "services/"), (nav_name, url)) + "\n]",
    }


PAGES = []

PAGES.append(service_page(
    "ac-repair", "Aircond Repair", "Aircond Repair",
    "Aircond repair,", "diagnosed before it is fixed",
    "A unit that has stopped cooling, stopped starting or failed mid-use gets inspected first, so the repair answers the actual fault rather than the symptom.",
    "svc-repair.webp",
    "What an aircond repair visit involves",
    ["Weak cooling, no cooling and a unit that will not start all have several possible causes. A dirty coil, a failing capacitor, a blocked drain line, a refrigerant leak and a control fault can each produce the same complaint, and each needs a different fix.",
     "So the visit begins with an inspection: the technician checks how the unit is behaving, works back to the component responsible, and explains what was found before any part is replaced. You hear what is wrong and what putting it right involves.",
     "Where a repair is not the sensible answer &mdash; an old unit with a failing compressor, for instance &mdash; we will say so rather than sell you a repair that will not last."],
    "Faults we are called out for",
    ["Unit runs but the room does not get cold", "Unit will not switch on or trips the breaker",
     "Water dripping from the indoor unit", "Ice forming on the coil or pipework",
     "Loud rattling, grinding or buzzing", "Unit short-cycles or shuts off by itself",
     "Remote or control board not responding", "Burning or musty smell when running"],
    "Repairs for homes and business premises",
    ["We work on wall-mounted splits in homes and apartments, and on the units keeping offices, shops and other commercial premises trading. For a business, downtime matters, so tell us your opening hours when you book and we will work around them.",
     "Parts are matched to your system. If a component needs ordering, you will be told what it is and how long it takes before we proceed."],
    "Aircond Repair in Kuala Lumpur | Ad Aircond Solution",
    "Aircond repair in Kuala Lumpur for units that have stopped cooling, will not start, leak water or trip the breaker. Inspection first, then the fix. Call +60178570744."))

PAGES.append(service_page(
    "ac-cleaning", "Aircond Cleaning", "Aircond Cleaning",
    "Deep cleaning that", "restores airflow",
    "Filters, coils, the blower wheel and the drain line are cleaned properly, so the unit moves the air it was built to move and sheds heat the way it should.",
    "svc-cleaning.webp",
    "Why cleaning changes how a unit performs",
    ["Dust loads up quickly in Kuala Lumpur. It settles on the filter first, then works through to the coil and the blower wheel, and as it builds the unit has to run longer to reach the same temperature.",
     "A clogged coil cannot shed heat properly and a coated blower wheel cannot push air. That shows up as weak cooling and a longer running time, and it is why a unit that is only a couple of years old can feel like it has lost its edge.",
     "Cleaning also clears the drain line. A blocked drain is the usual reason water ends up marking a wall, and it is far cheaper to clear than to repair the damage it causes."],
    "What gets cleaned",
    ["Filters washed and refitted", "Indoor coil cleaned down", "Blower wheel cleared of build-up",
     "Drain line flushed and checked", "Drain pan cleaned out", "Outdoor coil and fan cleaned",
     "Casing and louvres wiped down", "Cooling checked before we leave"],
    "How often it is worth doing",
    ["How often depends on the room rather than the calendar. A unit running most of the day, a home near a busy road, a kitchen, a shop floor or a household with pets will load up faster than a bedroom used only at night.",
     "We will tell you what the filters and coil actually looked like at this visit, so you can judge the right interval for your own space instead of guessing."],
    "Aircond Cleaning &amp; Servicing in KL | Ad Aircond Solution",
    "Aircond cleaning in Kuala Lumpur: filters, coil, blower wheel and drain line cleaned so airflow and cooling come back. Call +60178570744."))

PAGES.append(service_page(
    "ac-installation", "Aircond Installation", "Aircond Installation",
    "Installation done", "properly the first time",
    "Mounting, piping, drainage, electrical connection and commissioning &mdash; set up so the system performs as it was designed to from the day it is switched on.",
    "svc-installation.webp",
    "What a proper installation covers",
    ["How well an air conditioner performs has as much to do with how it was fitted as with the unit itself. Bracket placement, pipe run length, the fall on the drain line and the electrical connection all decide whether you get the cooling you paid for.",
     "We site the indoor unit where the air will actually reach the room, run the pipework and drain with the right fall, make the electrical connection safely, then commission the system and check it is cooling as it should before we leave.",
     "If you are still choosing a unit, tell us the room size and how it is used. We will tell you what capacity suits it &mdash; oversizing costs more to run and cools less comfortably than people expect."],
    "Included in an installation",
    ["Site check before the quote", "Indoor unit mounted and levelled",
     "Refrigerant pipework run and insulated", "Drain line run with correct fall",
     "Outdoor unit sited and secured", "Electrical connection made safely",
     "System vacuumed and commissioned", "Cooling verified before handover"],
    "Replacements and additional units",
    ["Replacing an old unit is often simpler than a first installation, because the pipe run and drain may be reusable. We check their condition first rather than assuming, since reusing a pipe run in poor condition causes problems later.",
     "Adding a unit to a home or premises that already has one is straightforward. Tell us where it needs to go and we will confirm what the run involves."],
    "Aircond Installation in Kuala Lumpur | Ad Aircond Solution",
    "Air conditioner installation in Kuala Lumpur: mounting, pipework, drainage, electrical connection and commissioning. Call +60178570744."))

PAGES.append(service_page(
    "ac-maintenance", "Aircond Maintenance", "Aircond Maintenance",
    "Maintenance that", "catches faults early",
    "Scheduled visits that keep a system running at its best and flag small issues while they are still small jobs.",
    "svc-maintenance.webp",
    "What maintenance is for",
    ["Most air conditioner failures announce themselves before they happen. A capacitor on its way out, a drain starting to block, a coil losing its ability to shed heat &mdash; each shows up as a change in how the unit behaves well before it stops.",
     "A maintenance visit is where those get noticed. The unit is cleaned, its operation checked, and anything heading for a problem is flagged while it is still cheap to deal with.",
     "The other half of it is running cost. A system kept clean reaches temperature sooner and runs for less time to hold it, which is the difference you feel on the bill rather than in the room."],
    "Covered at each visit",
    ["Filters and coil cleaned", "Drain line checked and flushed",
     "Airflow and cooling performance checked", "Refrigerant pressure checked",
     "Electrical connections inspected", "Fan and blower operation checked",
     "Outdoor unit cleaned and inspected", "Written note of anything to watch"],
    "Scheduled cover for premises with several units",
    ["Offices, shops and other premises running several units are easier to look after on a schedule than one call-out at a time. Units get attended in one visit, and you get a single picture of which ones are fine and which need attention.",
     "Tell us how many units you have and where they are, and we will set out what a visit covers and how often it is worth doing for your site."],
    "Aircond Maintenance in Kuala Lumpur | Ad Aircond Solution",
    "Scheduled aircond maintenance in Kuala Lumpur for homes and business premises. Cleaning, checks and early warning of faults. Call +60178570744."))

PAGES.append(service_page(
    "gas-refilling", "Gas Refilling", "Gas Refilling",
    "Refrigerant checked,", "then topped up",
    "Weak cooling often means low refrigerant. We check the system for the leak that caused it before refilling, so the gas stays in.",
    "svc-gas.webp",
    "Why we look for the leak first",
    ["Refrigerant is not consumed. A sealed system holds the same charge for years, so if the level has dropped it has escaped somewhere &mdash; a joint, a flare, a pipe run or the coil itself.",
     "Refilling without finding that leak means paying for gas twice: the cooling comes back for a while, then fades again as the charge escapes the same way it did the first time.",
     "So the visit starts with pressure readings and a leak check. If we find one, you are told where it is and what repairing it involves, and the system is refilled once it will hold the charge."],
    "Signs the charge may be low",
    ["Cooling has faded gradually over weeks", "Unit runs constantly without reaching temperature",
     "Ice forming on the pipework or coil", "Air from the vents is cool but not cold",
     "Hissing or bubbling from the indoor unit", "Higher electricity use with no change in habits",
     "Oily residue near pipe joints", "Cooling is worse on the hottest days"],
    "The right gas for your system",
    ["Different systems take different refrigerants, and they are not interchangeable. We identify what your unit is charged with and refill with that, to the pressure the manufacturer specifies rather than by feel.",
     "If the readings show the problem is not refrigerant at all &mdash; a dirty coil and a low charge can feel identical from the room &mdash; we will tell you that instead of selling you gas you do not need."],
    "Aircond Gas Refilling in Kuala Lumpur | Ad Aircond Solution",
    "Aircond gas refilling in Kuala Lumpur. Leak check and pressure test first, then refilled with the correct refrigerant. Call +60178570744."))

PAGES.append(service_page(
    "ac-electrical-service", "Aircond Electrical Service", "Aircond Electrical Service",
    "Electrical faults", "traced and handled safely",
    "From a failed capacitor to wiring and control faults &mdash; the electrical side of an air conditioner, diagnosed and repaired properly.",
    "svc-electrical.webp",
    "The electrical faults behind common symptoms",
    ["A unit that will not start, starts and stops, hums without running or trips the breaker is usually an electrical problem rather than a cooling one. Capacitors, contactors, fan motors, control boards and the wiring between them are all candidates.",
     "These are the faults where guessing is expensive. Replacing a control board when the capacitor was the problem costs several times what the actual fix would have. So the fault is traced to the component before anything is replaced.",
     "This is also the part of an air conditioner where working on it yourself is genuinely dangerous. Capacitors hold a charge after the power is off, and a unit that is tripping a breaker is telling you something that should not be reset and ignored."],
    "Electrical work we carry out",
    ["Capacitor testing and replacement", "Contactor and relay faults",
     "Fan and blower motor faults", "Control board diagnosis",
     "Wiring and terminal faults", "Units tripping the breaker",
     "Remote and sensor faults", "Power supply checks at the unit"],
    "When a breaker keeps tripping",
    ["A breaker that trips when the air conditioner runs is doing its job &mdash; something in the circuit is drawing more current than it should. Resetting it repeatedly does not fix the cause and is not safe.",
     "Switch the unit off at the isolator and call us. We will find what is drawing the current, whether that is the unit, its wiring or the supply, and put it right."],
    "Aircond Electrical Service in Kuala Lumpur | Ad Aircond Solution",
    "Aircond electrical repair in Kuala Lumpur: capacitors, wiring, control boards and units tripping the breaker. Call +60178570744."))


# --- services hub -----------------------------------------------------------

# The six cards are lifted from the homepage rather than written again, so the
# section has one layout wherever it appears and the two can never drift. Here
# each card is the link to its own service; <a> takes flow content, so the
# heading and the fault list carry over unchanged.
_home_cards = re.findall(r'<article class="svc\b[^"]*"[^>]*>.*?</article>', home, re.S)
assert len(_home_cards) == len(SERVICES), (len(_home_cards), len(SERVICES))

def _as_link(card, slug):
    card = re.sub(r'^<article class="svc\b[^"]*"[^>]*>',
                  f'<a class="svc svc--link reveal" href="/{slug}/">', card, count=1)
    return card[:-len('</article>')] + '</a>'

_svc_cards = "".join(
    "\n      " + _as_link(card, slug).replace("\n", "\n  ")
    for card, (slug, *_r) in zip(_home_cards, SERVICES))

PAGES.append({
    "dir": "services", "url": "services/", "nav": "services", "image": "svc-installation.webp",
    "title": "Aircond Services in Kuala Lumpur | Ad Aircond Solution",
    "description": "The six air conditioning services Ad Aircond Solution provides in Kuala Lumpur: repair, cleaning, installation, maintenance, gas refilling and electrical work.",
    "body": "\n".join([
        ahero("Our Services", "Complete Aircond care,", "all in one place",
              "Repair, cleaning, installation, maintenance, gas refilling and electrical work &mdash; for homes and business premises across Kuala Lumpur.",
              "svc-installation.webp",
              bc(("Home", "/"), ("Our Services", None))),
        f'''<section class="section services">
  <div class="wrap">
    <header class="sec-head services__head">
      <h2 class="hstack services__title">
        <span class="hstack__lead">Complete aircond</span>
        <span class="hstack__main">Repair, cleaning, installation &amp; maintenance</span>
        <span class="hstack__sub">For homes &amp; businesses in Kuala Lumpur</span>
      </h2>
      <span class="rule-ico" aria-hidden="true"><i class="rule-ico__line"></i><svg class="ico" aria-hidden="true"><use href="#i-snow"></use></svg><i class="rule-ico__line"></i></span>
      <p class="sec-head__text">Whichever one you need, the visit starts the same way &mdash; we look at the unit before recommending anything.</p>
    </header>
    <div class="svc-grid">{_svc_cards}
    </div>
  </div>
</section>''',
        problems(),
        article("Not sure which one you need?", [
            "Most people call about a symptom rather than a service, and that is the right way round. Weak cooling can be a dirty coil, a low refrigerant charge or a failing capacitor, and those are three different jobs.",
            "Tell us what the unit is doing &mdash; how it sounds, when it started, whether it cools at all &mdash; and we will tell you which service fits before anything is booked. If it turns out to be the cheaper job, that is the one we will quote."]),
        CTA,
    ]),
    "jsonld": crumbs(("Home", ""), ("Our Services", "services/")),
})


# --- about ------------------------------------------------------------------

def _pull(start, end):
    """Reuse a block that already exists on the homepage."""
    return between(start, end)

PAGES.append({
    "dir": "about", "url": "about/", "nav": "about", "image": "about.webp",
    "title": "About Us | Ad Aircond Solution, Kuala Lumpur",
    "description": "Ad Aircond Solution provides air conditioning repair, servicing, maintenance and installation for homes and businesses across Kuala Lumpur. Based at Titiwangsa Central.",
    "body": "\n".join([
        ahero("About Ad Aircond Solution",
              "The team keeping",
              "Kuala Lumpur cool.",
              "Air conditioning repair, cleaning, installation and maintenance for homes and business premises &mdash; from a workshop at Titiwangsa Central, Kuala Lumpur.",
              "cta-outdoor-unit.webp",
              bc(("Home", "/"), ("About Us", None))),
        # The homepage block carries Our Story and Our Mission cards. This page
        # covers both at more length in Our Journey and Vision & Mission below,
        # so the cards come out rather than saying it twice.
        drop(_pull('<!-- ============ ABOUT US ============ -->', '</section>\n'),
             '<div class="idcards">', '</div>\n\n'),
        vision_mission(),
        journey(),
        numbers(),
        capability(),
        team(),
        article("How we work", [
            "Every job starts with looking at the unit. A room that is not getting cold can point to a dirty coil, a blocked drain, a low refrigerant charge, a failing capacitor or a control fault, and the only way to know which is to inspect rather than assume.",
            "What we find gets explained in plain terms &mdash; what is wrong, what fixing it involves, and what it will take. If a repair is not worth doing on an old unit, we will say so.",
            "The work itself gets the same care as the diagnosis: the unit is left working properly, and the room is left as we found it."],
            checks("What you can expect", [
                "The unit inspected before anything is quoted",
                "The fault explained in plain language",
                "Parts matched to your system",
                "Work carried out at the agreed time",
                "The space left clean afterwards",
                "A straight answer when a repair is not worth it"])),
        CTA,
    ]),
    "jsonld": crumbs(("Home", ""), ("About Us", "about/")),
})


# --- contact ----------------------------------------------------------------

PAGES.append({
    "dir": "contact", "url": "contact/", "nav": "contact", "image": "step-contact.webp",
    "title": "Contact | Ad Aircond Solution, Kuala Lumpur",
    "description": "Call or WhatsApp Ad Aircond Solution on +60178570744, or send your details through the form. 14, Jalan Batu Bata, Titiwangsa Central, 50400 Kuala Lumpur.",
    "body": "\n".join([
        ahero("Contact", "Tell us what", "your aircond is doing",
              "Call, WhatsApp, or send the details through the form and we will confirm the service and a time that suits you.",
              "step-contact.webp",
              bc(("Home", "/"), ("Contact", None))),
        read("partials/booking.html"),
    ]),
    "jsonld": crumbs(("Home", ""), ("Contact", "contact/")),
})


if __name__ == "__main__":
    for page in PAGES:
        out = head(page)
        folder = os.path.join(ROOT, page["dir"])
        os.makedirs(folder, exist_ok=True)
        with open(os.path.join(folder, "index.html"), "w", encoding="utf-8") as fh:
            fh.write(out)
        print(f'/{page["url"]:28s} {len(out) // 1024:>3} KB')
    print(f"{len(PAGES)} pages built from index.html")
